apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mongo-hpa
  namespace: orders
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mymongo-mongodb
  minReplicas: 1
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10