apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: postgres-secret
  namespace: orders
spec:
  encryptedData:
    postgres-password: AgCRiDJaMZhuPc/4zlj+FvRjcA1LcyJtjcoKy3RyZi4BWdjFwwAJBo9Q5G6vLP9+aYjWnrCOJvd4jb5U8ZfMLTovZm0b2OFqiMUcmIKXd/mJeJE5oyNundCeF5AZlXDBIax0DevTSQmpIuFjX5SsGRjYjRKdRVyxLMcM40ytFtomQfOP+C1L8BAQ4a8P4klTMQFN+6g2UFayvJHyVvgdf9brCorDjmtUWXd/Xtt1+DOoTbvl51hwxC6dOIbIzxpdSDbd2dh008lz/ltdXxGg59mrstX66NngdwKlKTUm4l6cDS829eWRyn31mGYm7InqfiBaYPZMWpwMDvfrA09dVxRbz58OiOrb97YXWUlH4Oh9gwy4yAVNfA22evraWvsw8ek633Cd/dLXznnz7ef9UZ/Rkvp2Z04kT62qhzH+00iXJKSgKLX3HJni8XpLgNP0Eo3tsOrwMgxYJjwhJIOuMsOzyECxNGaNsQ16vYccqfD16J/QnsAPurGj6PwOlmEbQrXHLn1H3Lc9hNbbRl3jh+zBcy6aY3hNXODMLFVeYjsTZmi44TTSgrBgoATxIvlRzZBmJEMj7TW6mcSVaeV94dSUvN0a+1fNnlSuiZPgTqbo0hrUCUFPtyHf9fPUzPVz/V1YNZ9LUUAHPL+oyAR3hNmSdEWpRctysxr+KirvODeezbbkJewJ6uFZxUFHN89YxBd+6Rhm3FZwVSJK
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        app: postgres
      name: postgres-secret
      namespace: orders
    type: Opaque

