apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pgadmin-secret
  namespace: orders
spec:
  encryptedData:
    pgadmin-default-password: AgAq17pZcfqUGXwoDLfLWl5nELaXPgCDtbDYv5qrEmZi/dYZkSD8gX3+DVDhE16qaLKX/lqbxnWACxeVvGZKqeHnG40jnilCjW1tv8MoOfNukBxM392PLSLVZw4vB0JHsXjNWeSHp/ZD9T4LXw98hb4UZSw+DoAdPKLCWFELnfzT2gdxiyoncOTvNXlZ/jscKjD8yiSZHRFg10+atVK/aV3zaDBza99nQrVLPs8jQWFGVmDAXJ1fYfwOIoj6ZcznVwqcL2z0UfLLiHPq+HFqadjCkI0ULXAyWtujjModg8uY7rqmY6OxOu1fnRbcQUnnu3KTbLiK7C3+H6TA1ldMqVOP37Lp4DYucWILEsqGsKDn5zQt7DK7QVfyibM0/CzNWvPsHhNPg78mrzc4r/c6bGdnrfa9IooLRE3U0GQkOab/u2HOaB4kKGC/OygYbpWFHxEkROc+LkjkKvY0yus5oFEdLmOVkK5nFCvk/YZRD8PcOaLJw6Jz6Pcv0FK6b7vUcZG8MgZSvtr66UrrM9KoMEAC0RoHXeF/KO2NCVhPPlb83LXpl2L/cJuI/CbW9M71Xzfq+DXG8C1XK1yVT+Ng72UICvoJ8QNnMbFcb1n28Eutx2dlTV7hETxP/UdiWtJmUIcHIqKEMRtCZOTeKLTJXm+2uJIdY5lRoZklfYvoLJ+dQIya9CHUSwN7MX6jS1JhpZz2siorzA==
  template:
    metadata:
      creationTimestamp: null
      name: pgadmin-secret
      namespace: orders
    type: Opaque

