apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: orders
spec:
  encryptedData:
    postgres-password: AgBnwyAE7VDx3eqRv43Fmnm8bt9mdYLt5mElFcs/Bgc03U7DbcZXks6rs7oQqQFkyBvWMVXByfYG4ZTxXqwApOO4CZs8iTM9rvp0HFMVREbU7maArqmCBlCh1Ys/gGmQKklMxaG4kICQ8xGxLvZlvVK9ea20N8YpkvJmaulY93wBnKUVnn3WPMgShpRSFIVjGWUJzRnEEtu0ji81HKABWY+NZi9dYhFyigevhA0MKSFHIeD88vQavXcBI1BVZBPVWzxhL+HIz8aBOW3QLB3PunJolcwhqAANZY142027OVzgMLHv5h1J7lJFXGP6TAvw5vdIAsm4G0cDlI55IwwslVnq0P6eJfpmeuKcNPenKX+7UcxlZCHhhE5Zj5+YSOS79fGelpkGdCz3s7e6vKD0JRyOgqaj4tBpGYKoPjB8deZBBevRh2mnjV5OjByLS+fWQnuyEcHb2lkVhZu6Z+mO6JMmQdvokS56l12mph52viNxCvFuaIgTPEY6sdrentppOE4arxZbrOzAYAVmCprKdkhB2R1lLLR512Ifr/+eRksnHa+G65Fp6bi1YUo31gUTKgjLnqGkyFD5fGv22r9ecRfwNzvL+6Hh9gJTlJhre/Yb/g4BlkfeZhsIjsawZbeQhiyr0tpaAjBUqoF6dGntTqhTwgRehD20+Y1LW6qqD1W9s/i8Ewdp5GOoxY0ZV5LDfD/sMShhVV6evpmt
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres
      name: postgres-secret
      namespace: orders
    type: Opaque

