apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: k8sproject

# Example configuration for the webserver
# at https://github.com/monopole/hello
commonLabels:
  app: hello

resources:
- k8s-secrets.yaml
- orders/mongo-db.yaml
- orders/mongo-express.yaml


# helmCharts:
# - name: kube-prometheus-stack
#   repo: https://prometheus-community.github.io/helm-charts
#   version: "47.0.0"
#   releaseName: prom
#   namespace: monitoring
#   valuesFile: monitoring/prom.yaml
# - name: loki
#   repo: https://grafana.github.io/helm-charts
#   version: "5.8.4"
#   releaseName: loki
#   namespace: monitoring
#   valuesFile: monitoring/loki.yaml
# - name: promtail
#   repo: https://grafana.github.io/helm-charts
#   version: "6.11.5"
#   releaseName: promtail
#   namespace: monitoring
#   valuesFile: monitoring/promtail.yaml
# - name: opentelemetry-collector
#   repo: https://open-telemetry.github.io/opentelemetry-helm-charts
#   version: "0.61.0"
#   releaseName: opentelemetry-collector
#   namespace: monitoring
#   valuesFile: monitoring/otel-collector-values.yaml