apiVersion: v1
kind: Namespace
metadata:
  name: curstomer-product
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: orders
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability