
apiVersion: v1
kind: Pod
metadata:
  name: secret-dotfiles-pod
  namespace: orders
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: rust-crud-secret
  containers:
    - name: dotfile-test-container
      image: registry.k8s.io/busybox
      command:
        - sleep
        - "300"
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secret-volume"