mode: deployment
ports:
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false
config:
 receivers:
   jaeger: null
   prometheus: null
   zipkin: null
 exporters:
   jaeger:
     endpoint: simplest-collector:14250
     tls:
       insecure: true
   logging:
     loglevel: debug
 service:
   telemetry:
     logs:
       level: debug
   pipelines:
     traces:
       receivers:
         - otlp
       exporters:
         - jaeger
         - logging
     metrics: null
     logs: null
service:
 type: LoadBalancer
image:
 repository: otel/opentelemetry-collector
 tag: "latest"
command:
 name: otelcol