apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: test-pg-hpa
  namespace: customer-product
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mypostgres-postgresql
  minReplicas: 3
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10