apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: orders
spec:
  template:
    spec:
      containers:
        - name: python-app
          image: konkerama/k8s-application:5aa653b3d7c405571292d5b6fd7824f998a45f98
          env:
          - name: ENV
            value: "dev"
          - name: ENABLE_TELEMETRY
            value: "False"
