apiVersion: v1
kind: Namespace
metadata:
  name: customer-product
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: orders
  # labels:
  #   istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd