apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-crud
  namespace: orders
spec:
  template:
    spec:
      containers:
        - name: rust-crud
          image: konkerama/rust-crud-api:0.0.5
          env:
            - name: ENV
              value: dev
            - name: ENABLE_TELEMETRY
              value: 'False'
