apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: orders
spec:
  template:
    spec:
      containers:
        - name: python-app
          image: konkerama/rust-crud-api:0.0.6
          env:
            - name: ENV
              value: dev
            - name: ENABLE_TELEMETRY
              value: 'False'
