apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: db-mgmt
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
  - repoURL: https://github.com/konkerama/k8s-project.git
    targetRevision: HEAD
    path: db-mgmt
  destination:
    server: https://kubernetes.default.svc
    namespace: orders
  syncPolicy:
    automated:
      prune: true
      selfHeal: true