apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
  - repoURL: https://charts.bitnami.com/bitnami
    chart: mongodb
    path: k8s
    targetRevision: 13.15.5
    helm:
      valueFiles:
        - $values/helm-values/orders-mongo.yaml
  - repoURL: 'https://github.com/konkerama/k8s-project.git'
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: orders
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true