apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  namespace: customer-product
  labels:
    app: postgres
data:
  postgres-dbname: mydb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  namespace: orders
  labels:
    app: postgres
data:
  postgres-dbname: mydb