apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: orders
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: parameterstore
    kind: SecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
  data:
  - secretKey: postgres-password
    remoteRef:
      key: /k8s-project/secrets
      property: postgres-secret.postgres-password