apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: orders
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: parameterstore
    kind: SecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
  data:
  - secretKey: postgres-password
    remoteRef:
      key: /k8s-project/secrets
      property: postgres-secret.postgres-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin-secret
  namespace: orders
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: parameterstore
    kind: SecretStore
  target:
    name: pgadmin-secret
    creationPolicy: Owner
  data:
  - secretKey: pgadmin-default-password
    remoteRef:
      key: /k8s-project/secrets
      property: pgadmin-secret.pgadmin-default-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-secret
  namespace: orders
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: parameterstore
    kind: SecretStore
  target:
    name: mongodb-secret
    creationPolicy: Owner
  data:
  - secretKey: mongodb-passwords
    remoteRef:
      key: /k8s-project/secrets
      property: mongodb-secret.mongodb-passwords
  - secretKey: mongodb-root-password
    remoteRef:
      key: /k8s-project/secrets
      property: mongodb-secret.mongodb-root-password
  - secretKey: mongodb-metrics-password
    remoteRef:
      key: /k8s-project/secrets
      property: mongodb-secret.mongodb-metrics-password
  - secretKey: mongodb-replica-set-key
    remoteRef:
      key: /k8s-project/secrets
      property: mongodb-secret.mongodb-replica-set-key