apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: orders
spec:
  data:
  - secretKey: postgres-password
    remoteRef:
      key: /k8s-project/secrets
      property: postgres-secret.postgres-password