apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: parameterstore
  namespace: external-secrets
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-west-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key